version: "3.8"
services:
    db:
        container_name: mydb
        image: mysql:8.0
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: mydb
            MYSQL_USER: user 
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
    app:
        container_name: myapp
        links:
            - "db"
            - "redis"
        build: ./
        ports:
            - "5000:5000"
        volumes:
            - .:/app   
    redis:
        container_name: myredis
        image: redis:latest
        ports:
            - "6378:6379"
        volumes:
            - redis_data:/data    
    celery_worker:
        build: ./
        command: celery -A app.celery_app.celery worker --loglevel=info
        volumes:
            - .:/app
        depends_on:
            - redis
    celery_beat:
        build: ./
        command: celery -A app.celery_app.celery beat --loglevel=info
        volumes:
            - .:/app
        depends_on:
            - redis


volumes:   
  db_data:
  redis_data:
  celery_data: